### PR TITLE
Copyright to page bottom

### PR DESCRIPTION
**Pull request by pjchong91**
I noticed the footer (copyright) floats around the bottom 2/3 of the page.  I lightly adjusted some CSS to anchor the footer to the bottom of the page in mobile and tablet views.

### CODE REVIEW

**Comment by rcass** [comment]
Looks like a good change to me 👍 I recommend merging this into your project @AndreiEgorov

**Comment by AndreiEgorov** [comment]
Hey @pjchong91 and @rcass thank you for the recommendation. I have made some changes to the scss files already, thus could not merge directly. So I added the proposed editions manually.

**Comment by rcass** [comment]
I assume these are the changes in this commit c4eb73bb389886b03c2a108abbd945f45beb5479

Looks ok to me

**Comment by AndreiEgorov** [comment]
Yep,

I applied those.

**Pull request closed without merging**
